# Generated by Django 4.0.3 on 2022-03-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
