# Generated by Django 4.0.3 on 2022-03-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='device',
        ),
    ]
