# Generated by Django 4.0.3 on 2022-04-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='transactions_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
